export const APP_CATEGORIES = [
  "Debits",
  "Withdrawals",
  "Rent",
  "Salary",
  "University",
  "School",
  "Groceries",
  "Petrol",
  "Car service/stuff",
  "Treat",
  "Health",
  "Investment",
  "Gifts",
  "Clothes",
  "Toiletries",
  "DIY",
  "Home",
  "Guilt-free",
  "Fees",
  "Interest",
  "Transfer",
  "Uncategorised",
] as const;

export type AppCategory = (typeof APP_CATEGORIES)[number];

export const BANK_CATEGORIES = [
  "Groceries",
  "Fuel",
  "Cellphone",
  "Fees",
  "Medical Aid",
  "Vehicle Insurance",
  "Life Insurance",
  "Clothing & Shoes",
  "Cash Withdrawal",
  "Restaurants",
  "Investments",
  "Pharmacy",
  "Uncategorised",
  "Home Maintenance",
  "Garden",
  "Personal Care",
  "Sport & Hobbies",
  "Other Personal & Family",
  "Licence",
  "Holiday",
  "Other Income",
  "Donations",
  "Transfer",
  "Interest",
  "Digital Payments",
  "Internet",
  "Education",
  "Furniture & Appliances",
  "Doctors & Therapists",
  "Other Medical",
  "Online Store",
  "Alcohol",
  "Gifts",
  "Bonus",
  "Software/Games",
  "Home Improvements",
  "Refunds",
  "Digital Subscriptions",
  "Home Insurance",
  "Vehicle Maintenance",
] as const;

export type BankCategory = (typeof BANK_CATEGORIES)[number];
